### ISSUE TITLE
Default pattern to search pg bin not working

### ISSUE THREAD

**Issue by zabrowarnyrafal** [bt-skyrise/Postgres2Go#25]

**Comment by paw-sad** [comment]
I'm on it

**Comment by zabrowarnyrafal** [comment]
gr8 - thx

**Comment by marcinbudny** [comment]
The default search pattern for Windows is `pg-dist\pqsql-win64*\bin` while the actual path in tools is `pgsql-10.1-windows64-binaries`. This should be an easy fix.

**Comment by marcinbudny** [comment]
There seems to be another issue with wildcard matching in path, so you may want to look at that. But the search pattern provided as `pg-dist\pgsql-10.1-windows64-binaries\bin` seems to work ok.
